### ISSUE TITLE
getmeminfo fails when running Node-DC-EIS using ab as client

### ISSUE THREAD

**Issue by sushmakt** [Node-DC/Node-DC-EIS#61]
When Node-DC-EIS is started with manual starts of servers, and using ab as client instead of python, consistently seeing the following error for all node server instances.
"[09-09-2017 07:15:45] Call to get server memory data failed.
HTTPConnectionPool(host='192.168.1.x', port=9001): Max retries exceeded with url: /getmeminfo (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7ffff31df850>: Failed to establish a new connection: [Errno 11192.168.1.200] ETIMEDOUT',))"

However, doing a "curl --noproxy 192.168.1.x -v http://192.168.1.x/9001/getmeminfo" succeeds. 
192.168.1.x being the IP address of the node server.

Expected behaviour: The workload should successfully complete with this setup:ab as client, node as server and mongodb as database.

**Comment by egalli** [comment]
I seem to be unable to reproduce this issue. Are you using cluster or microservices? How are you using ab instead of the runspec? Did you modify any of the server settings?

Run using ApacheBench:
```
% cd Node-DC-EIS-cluster
% node server-cluster.js&
Starting a single instance of Node.js process with (pid: 17075)
********************************
Server running at port: 9000
********************************
Mongoose connected to the database
% curl 127.0.0.1:9000/loaddb
Constructing list of first names
Constructing list of last names
Constructing list of Addresses
{"message":"10000 records are populated"}
% curl 127.0.0.1:9000/getmeminfo
{"memoryInfo":{"rss":447.6875,"heapTotal":393.5,"heapUsed":359.9221725463867}}
% ab -n 1000 127.0.0.1:9000/employees/id
This is ApacheBench, Version 2.3 <$Revision: 1757674 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests
Completed 800 requests
Completed 900 requests
Completed 1000 requests
Finished 1000 requests


Server Software:
Server Hostname:        127.0.0.1
Server Port:            9000

Document Path:          /employees/id
Document Length:        270001 bytes

Concurrency Level:      1
Time taken for tests:   21.224 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      270229000 bytes
HTML transferred:       270001000 bytes
Requests per second:    47.12 [#/sec] (mean)
Time per request:       21.224 [ms] (mean)
Time per request:       21.224 [ms] (mean, across all concurrent requests)
Transfer rate:          12433.76 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       0
Processing:    15   21   9.9     16     101
Waiting:       15   21   9.9     16     101
Total:         15   21   9.9     16     101

Percentage of the requests served within a certain time (ms)
  50%     16
  66%     16
  75%     17
  80%     36
  90%     37
  95%     38
  98%     44
  99%     52
 100%    101 (longest request)
```

**Comment by uttampawar** [comment]
@egalli Following detail contain step to reproduce the issue. 

0) Problem is visible only with runspec.py execution flow, so you need to test it using this client.
1) Make sure you are doing GET only request (clients confg.json file)
  - "url_params":
   {
    "get_ratio": "100",
    "post_ratio":"0",
    "delete_ratio":"0"
  },

Please make following changes to the controllers/employees_controller.js file,

1) exports.findByZipcode()
add return call before Employee.find('address.zipcode' .....) query (line 423) as, 
return sendResponse(res, 200, null); /* This by passes the complete query execution */

2) exports.findById()
add return call before Employee.findOne() query (line 484) as, 
return sendResponse(res, 200, null); /* This by passes the complete query execution */

3) exports.findByName()
add return call before Employee.find() query (line 524) as, 
return sendResponse(res, 200, null); /* This by passes the complete query execution */

Since we are doing GET only request we don't care about the response, that means code should work these changes.

**Comment by uttampawar** [comment]
@egalli Any update?
